import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ChatScreen from '../components/ChatScreen'
import SideBar from '../components/SideBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Chat in a Box: ChatterBox</h1>
      <SideBar></SideBar>
  
    </div>
  )
}

export default Home
