import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import MainChat from "../components/MainChat";
import SideBar from "../components/SideBar";
import { db } from "../firebase";

const ChatContainer = styled.div`
  flex: 1;
  overflow: scroll;
  height: 100vh;
  ::-webkit-scrollbar {
    display: none;
  }
  -ms-overflow-style: none;
  scrollbar-width: none;
`;
const Container = styled.div`
  display: flex;
`
const Header = styled.h1`
text-align: center;
`
const Home: NextPage = ({ mainMessages }: any) => {
  return (
    <div>
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Container>
      <SideBar></SideBar>
      <ChatContainer><MainChat messages={mainMessages}></MainChat></ChatContainer>
      </Container>
    </div>
  );
};

export default Home;

export async function getServerSideProps(context: { query: { id: string } }) {
  
  const ref = db.collection("mainchat");
 
  //prep messages
  const mainChatMessages = await ref
    .orderBy("timestamp", "asc").get();
  
  const messages = mainChatMessages.docs
    .map((doc: any) => ({
      id: doc.id,
      ...doc.data(),
    }))
    .map((messages) => ({
      ...messages,
      timestamp: messages.timestamp.toDate().getTime(),
    }));
  //prep the chats
  // const chatRes = await ref.get();
  // const chat = {
  //   id: chatRes.id,
  //   ...chatRes.data(),
  // };

  return {
    props: {
      mainMessages: JSON.stringify(messages),
    },
  };
}
